#Custom items
#Default localization
custom-items:
  flag-pillar:
    material: STICK
    name: "§aСтолб флага"
    lore:
      - "§7Используется в создании флага"
  flag-cloth:
    material: FLOWER_BANNER_PATTERN
    name: "§aЗнамя"
    lore:
      - "§7Используется в создании флага"
  flag:
    material: END_ROD
    name: "§9§lФлаг"
    lore:
      - "§7Для установки флага"
      - "§7используйте ПКМ"

#Flags settings
#Value that means what protection distance will be
#Territory with size (protection*2)x(protection*2) will be protecting
protection-distance: 30
#Block material of knob
flag-knob-material: GOLD_BLOCK
#The worlds where flags available
#WORLDS:
#-world
#-the_nether
#-the_end_world
available-worlds:
  - world
#Blocks that can be placed on stranger flag zone
available-blocks:
  - TNT
  - CAKE
  - LADDER
  - TRAPPED_CHEST
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - SILVER_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BLOWN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX
  - ENDER_CHEST
  - TORCH
#Flag start strength
start-flag-strength: 10